### ISSUE TITLE
README Example Fails

### ISSUE THREAD

**Issue by jbitton** [hbmartin/pytube3#12]
Hi there!

I'm trying to use pytube and came across your fork. However, the example in your README raises an exception. I'd really appreciate if this could be fixed!

I'm using Python 3.7.5 on a Mac:

```
Python 3.7.5 (v3.7.5:5c02a39a0b, Oct 14 2019, 18:49:57) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 94, in __init__
    self.descramble()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 142, in descramble
    self.player_config_args, fmt, self.js  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/mixins.py", line 56, in apply_signature
    signature = cipher.get_signature(js, stream["s"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/cipher.py", line 271, in get_signature
    var, _ = transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)
```

**Comment by swiftyy-mage** [comment]
YouTube just changed their JS like 2 hours ago roughly, it's fine someone always ends up fixing it eventually.

**Comment by hbmartin** [comment]
I'll dig in, might take a few days.
@swiftyy-mage think this might be related to https://github.com/hbmartin/pytube3/issues/9 ?

**Comment by movraxrsp** [comment]
I have some time the next few days, this will be fun....

**Comment by hbmartin** [comment]
@movraxrsp @swiftyy-mage added a new regex in latest commit to `master`, can you check that it works for you?

**Comment by swiftyy-mage** [comment]
Yup you fixed it, and pretty damn quickly too! Great stuff! I was gonna reply to your comment after I got home today, but I needed to take some time to really look over and see.

**Comment by hbmartin** [comment]
@swiftyy-mage no I'm lazy, copied the fix from that other project 😄 
... still need to dig into #9 and understand what's going on there

**Comment by movraxrsp** [comment]
efficient, not lazy

**Comment by swiftyy-mage** [comment]
Well no need to reinvent the wheel! I'm looking into #9 now.

**Comment by movraxrsp** [comment]
i'm looking at #9 now too, especially since I didn't get started in time to work on the new re in cipher

**Comment by picrazy2** [comment]
I'm getting this exact error using pytube, when the downloading was working an hour ago. Did something change again?

**Comment by tomaszkob89** [comment]
This fix worked for me:
https://github.com/H4KKR/pytubeX/pull/5/commits/f35b948afe3029ef60b427a1afd14e4551f2b7a7

**Comment by picrazy2** [comment]
> This fix worked for me:
> [H4KKR/pytubeX@f35b948](https://github.com/H4KKR/pytubeX/commit/f35b948afe3029ef60b427a1afd14e4551f2b7a7)

Worked for me! Thanks!
