### ISSUE TITLE
Investigate restricted video issues

### ISSUE THREAD

**Issue by hbmartin** [hbmartin/pytube3#20]
https://github.com/nficano/pytube/issues/424
https://github.com/nficano/pytube/pull/370/files
https://github.com/nficano/pytube/pull/372/files

**Comment by swiftyy-mage** [comment]
Will investigate this next. Imo, pytube isn't complete until it can download every YouTube video out there. I'll see how other projects are doing it and implement it here. Might take a while.

**Comment by hbmartin** [comment]
https://github.com/hbmartin/pytube3/pull/48
