### ISSUE TITLE
Having issues with on_complete and on_progress callbacks

### ISSUE THREAD

**Issue by RainbowAsteroids** [hbmartin/pytube3#53]
```
import pytube
video = pytube.YouTube('https://www.youtube.com/watch?v=dTgQSSo0310')
video.register_on_complete_callback(lambda a,b: print('Hello, World!'))
video.streams.first().download()
```

Nothing printed to the console :(

**Comment by movraxrsp** [comment]
Runs fine for me. Copied your code into a module file. In VS Code, ran it without debugging, video downloaded ok. "Hello, World!" printed on completion.
![image](https://user-images.githubusercontent.com/59103996/74406109-9ae78300-4de3-11ea-8e51-656bbd8cc58c.png)

Maybe provide more details: versions, environment.

**Comment by hbmartin** [comment]
@RainbowAsteroids this seemed to work for me as well. I'm experimenting with some related changes here: https://github.com/hbmartin/pytube3/pull/54
Maybe you can try that branch and let us know your results?

**Comment by RainbowAsteroids** [comment]
Just as an FYI before I try installing from source:

```
[rainbow@HP-Motherboard ~]$ cat test.py
import pytube

video = pytube.YouTube("https://www.youtube.com/watch?v=dTgQSSo0310")
video.register_on_complete_callback(lambda a,b: print('Hello, World!'))
video.streams.first().download()
[rainbow@HP-Motherboard ~]$ python test.py
[rainbow@HP-Motherboard ~]$ pip list | grep -e pytube
pytube3                      9.6.1   
[rainbow@HP-Motherboard ~]$ python --version
Python 3.8.1
[rainbow@HP-Motherboard ~]$ uname -a
Linux HP-Motherboard 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux
```

**Comment by RainbowAsteroids** [comment]
I tried again but I uninstalled pypi version and cloned the `live-and-complete-fixes` branch with the 3584e5b commit and ran `sudo python setup.py install`. No dice.

**Comment by hbmartin** [comment]
@RainbowAsteroids thanks for the info. What happens if you try downloading the video with `pytube3` on the command line?

**Comment by RainbowAsteroids** [comment]
```
[rainbow@HP-Motherboard Documents]$ pytube3 https://www.youtube.com/watch?v=dTgQSSo0310
Loading video...
[rainbow@HP-Motherboard Documents]$ ls
[rainbow@HP-Motherboard Documents]$ 
```
Using the version live on Pypi, nothing happens...

**Comment by swiftyy-mage** [comment]
That's weird. I tried it on two fresh venv's (3.6.10 & 3.8.1), fresh pytube3 install and it worked fine for me both times. I did notice though, that once I had already downloaded the video, running the script again did not print the "Hello, World!". Maybe try running it in a directory which doesn't already have the video?

**Comment by RainbowAsteroids** [comment]
@hbmartin Make a reminding issue to make the library throw a warning or call some callback whenever the video is already downloaded, because that was what was going wrong.

**Comment by hbmartin** [comment]
@swiftyy-mage gets it right again... @RainbowAsteroids good call out, we'll get this done
