### ISSUE TITLE
Unable to find video duration. KeyError: player_config_args['player_response']

### ISSUE THREAD

**Issue by GrautDevelopes** [hbmartin/pytube3#57]
I started having this issue fairly recently. I encountered it after trying to grab the length of the video with this snippet:
`youtubeLength = int(yt.player_config_args['player_response']['videoDetails']['lengthSeconds'])`
Here's a traceback. Happens on all videos for me, but here's [one ](https://www.youtube.com/watch?v=xCy--f9cUjY) of them.
```
Traceback (most recent call last):
  File "SampleFetchYT.py", line 78, in downloadYouTube
    youtubeLength = int(yt.player_config_args['player_response']['videoDetails']['lengthSeconds'])
KeyError: 'player_response'
```

I tracked down the error and believe it to be in this function.
https://github.com/nficano/pytube/blob/66b33803adb1780a84c7cf75ab8968bd5f0fcffc/pytube/extract.py#L176

I dumped the contents of the `player_config_args` variable, and the `player_response` surely wasn't there. I'd place a bet this is YouTube always changing things again. The only occurrence of the length in seconds was in the stream url's dur parameter.

`otfp=1&dur=211.603&lmt=1581533453582091`

Is this the only way to get the video length now, or is there a cleaner way?

**Comment by hbmartin** [comment]
You can use the `yt.length` property for this 😄 We don't support external access to `player_config_args`
